### ISSUE TITLE
6주차 실습과제 2번 질문이 있습니다. 

### ISSUE THREAD

**Issue by J1miin** [Park-MinJe/23-1_Programming-Fundamentals_02#34]
1. 메뉴 1번을 통해 개설하는 계좌 변수 세 개를 0으로 초기화하고 비교 해서 개설 해도 되는건가요?
2. 메뉴 1번에서 반복을 할 때, 계좌 세 개를 한 번에 만들고 나서 처음 메뉴(1-5)로 돌아가는 건지, 아니면 계좌 하나 만들어도 다시 메뉴로 돌아가는 실행인지 궁금합니다!

**Comment by Park-MinJe** [comment]
1. 계좌 id 변수를 말씀하시는 거라면, 0보다는 확실하게 아이디가 될 수 없는 -1 같은 형태로 초기화하는 것을 추천합니다.
2. 모든 기능은 한 번 실행할 때 하나의 계좌에 대해서만 영향을 미칠 수 있습니다. 따라서 계좌 하나를 개설하고 처음 메뉴로 돌아가는 형태로 작성해주시면 됩니다.
