### ISSUE TITLE
7주차 추가문제 질문

### ISSUE THREAD

**Issue by kelly09876** [Park-MinJe/23-1_Programming-Fundamentals_02#35]
6주차 실습 문제에서 어느 부분을 수정해야 하나요? 같은 건가요?

**Comment by Park-MinJe** [comment]
같은 겁니다. 하지만 완전히 똑같이 작성하지는 마시고 주석 처리를 더 하거나, 개선한 점이 있다면 개선한 내용에 대해 보고서를 쓰시면 됩니다.
