### ISSUE TITLE
10주차 실습2번문제 질문입니다.

### ISSUE THREAD

**Issue by jipal-0430** [Park-MinJe/23-1_Programming-Fundamentals_02#37]
실습2번 문제를 풀며 프로그램이 어떤식으로 동작이 이루어 지는지  헷갈립니다.
혹시 프로그램의 출력형태가 어떻게 되는지 올려주실 수 있으실까요?

**Comment by Park-MinJe** [comment]
너무 늦게 확인했네요..

백준 문제
https://www.acmicpc.net/problem/11650

참고하시면 됩니다!
